### ISSUE TITLE
Net Framework Support

### ISSUE THREAD

**Issue by exxorcist** [FaakhirRehman/Social-Messaging-App#1]
Net Framework 4 will be deprecated in a few months what are your suggestions for future proofing this app?

**Comment by FaakhirRehman** [comment]
I'm using .NET SDK 7 for this project. Please refer to the [global.json](https://github.com/FaakhirRehman/Social-Messaging-App/blob/main/global.json) file. You can learn more about .NET 7 [here](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-7)
